### ISSUE TITLE
快速开始的配置?

### ISSUE THREAD

**Issue by swuecho** [lanthora/candy#326]
```
version: '3'
services:
  candy:
    image: docker.io/lanthora/candy:latest
    privileged: true
    network_mode: host
    volumes:
      - /var/lib/candy:/var/lib/candy
```

比如我在 local(内网) 和 remote server (公网 ip: 192.225.196.101) 都启动了docker container, 怎么快速配置?

没用过此类的软件,不知道怎么上手. 多谢
